// Action types.
export const PET_DETAILS = {
  SET_LOADING: 'LOADING_PET_DETAILS',
  FETCH: 'FETCH_PET_DETAILS',
  FETCH_SUCCESS: 'FETCH_PET_DETAILS_SUCCESS'
};

export const ERROR = {
  THROW: 'THROW_ERROR',
  RESET: 'RESET_ERROR'
};
